=== wikianesthesia/mediawiki-extensions-UserAchievements/resources/schema/achievement.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "description": "UserAchievements achievement.json schema. An achievement's achievement.json definition, along with all supporting files (internationalization messages, images, etc.) must be contained in a subdirectory of the \"achievements\" directory of the UserAchievements extension. The name of this subdirectory defines the case-sensitive id of the achievement. For consistency, many fields use the same names as the extension.json schema. However, only a limited subset of these fields are supported for achievements.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "The id of the achievement. This must be unique across all achievements. If not specified, will default to the class name (without the namespace)."
    },
    "class": {
      "type": "string",
      "description": "The full class name (including namespace) of the achievement",
      "required": true
    },
    "classfile": {
      "type": "string",
      "description": "The relative path to the achievement class php file. If not specified, will default to the class name (without the namespace) in the same directory as the json definition."
    },
    "version": {
      "type": "string",
      "description": "The version of this release of the achievement."
    },
    "author": {
      "type": [
        "string",
        "array"
      ],
      "description": "Achievement's authors.",
      "items": {
        "type": "string"
      },
      "default": ""
    },
    "name": {
      "type": "string",
      "description": "Raw display name of the achievement. If not specified, this will default to the achievement's id."
    },
    "namemsg": {
      "type": "string",
      "description": "i18n message key of the achievement's name. If not specified, will attempt to use the message key \"userachievements-ACHIEVEMENTID-name\". If a valid message is defined, this will take precedence over the value of \"name\"."
    },
    "description": {
      "type": "string",
      "description": "Raw description of the achievement."
    },
    "descriptionmsg": {
      "type": "string",
      "description": "i18n message key of the achievement's description. If not specified, will attempt to use the message key \"userachievements-ACHIEVEMENTID-desc\". If a valid message is defined, this will take precedence over the value of \"description\"."
    },
    "priority": {
      "type": "integer",
      "description": "The number of levels of the achievement which can be awarded.",
      "default": 100
    },
    "secret": {
      "type": "boolean",
      "description": "Should the achievement be listed as available prior to being achieved.",
      "default": false
    },
    "levels": {
      "type": "integer",
      "description": "The number of levels of the achievement which can be awarded.",
      "default": 1
    },
    "color": {
      "type": "string",
      "description": "The primary color of the achievement."
    },
    "badges": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string"
          },
          "namemsg": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "descriptionmsg": {
            "type": "string"
          },
          "secret": {
            "type": "boolean",
            "description": "Should the badge be listed as available prior to being achieved.",
            "default": false
          },
          "color": {
            "type": "string",
            "description": "The primary color of the badge."
          },
          "requiredStats": {
            "type": "object",
            "description": "The minimum required stats to automatically award the badge. The properties correspond to the ids of the stat with the minimum required value for the stat as values."
          },
          "media": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "image": {
                "type": "string"
              },
              "thumbnail": {
                "type": "string"
              },
              "icon": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "stats": {
      "type": "object",
      "description": "Defines the stats and default values used by this achievement, with the stat ids as properties and the default values as values.",
      "items": {
        "type": "string"
      }
    },
    "config": {
      "type": "object",
      "description": "Configuration options for this achievement. Unlike the extension.json definition of this field, this should be a simple object with the variable names as properties and default values as values.",
      "items": {
        "type": "string"
      }
    },
    "AutoloadClasses": {
      "type": "object",
      "description": "A list of classes and files to autoload. This should be a simple object with the class name as properties and the local path to the class files function as values.",
      "items": {
        "type": "string"
      }
    },
    "AvailableRights": {
      "type": "array",
      "description": "User rights added by the class.",
      "items": {
        "type": "string"
      }
    },
    "GroupPermissions": {
      "type": "object",
      "description": "Default permissions to give to usergroup. This should be a two dimensional object with the usergroup as the first dimension's properties, the rights as the second dimension, and a boolean to grant or deny the right as values.",
      "items": {
        "type": "object"
      }
    },
    "Hooks": {
      "type": "object",
      "description": "MediaWiki hooks which should trigger an attempt to achieve the achievement for the user. This should be a simple object with the hook as properties and the callback function as values. For default behavior, set the value to \"tryAchieve\"",
      "items": {
        "type": "string"
      }
    },
    "MessagesDirs": {
      "type": "array",
      "description": "Directory paths containing JSON internationalization data. Unlike the extension.json definition of this field, this should be a simple array of paths relative to the achievement's root.",
      "items": {
        "type": "string"
      }
    },
    "ResourceModules": {
      "type": "object",
      "description": "ResourceModules to register",
      "items": {
        "type": "object"
      }
    },
    "ResourceFileModulePaths": {
      "type": "object",
      "description": "Specifies the default paths to use for all ResourceLoader file modules.",
      "additionalProperties": false,
      "properties": {
        "localBasePath": {
          "type": "string"
        },
        "remoteExtPath": {
          "type": "string"
        },
        "remoteSkinPath": {
          "type": "string"
        }
      }
    }
  }
}

=== wikianesthesia/mediawiki-extensions-UserAchievements/achievements/InauguralMember/achievement.json
{
  "author": [
    "Chris Rishel"
  ],
  "version": "1.0",
  "priority": 25,
  "levels": 2,
  "color": "#9fc96b",
  "config": {
    "EpochStart": "",
    "EpochLength": "1 year",
    "IncludeDeletedRevisions": false,
    "IncludeNamespaces": [],
    "IncludeNullRevisions": false,
    "IncludeRedirects": true,
    "RequireEmailConfirmation": true
  },
  "MessagesDirs": [
    "i18n"
  ]
}

=== wikianesthesia/mediawiki-extensions-UserAchievements/achievements/ArticlesEdited/achievement.json
{
  "class": "MediaWiki\\Extension\\UserAchievements\\Achievement\\ArticlesEdited",
  "version": "1.0",
  "author": [
    "Chris Rishel"
  ],
  "priority": 150,
  "levels": 5,
  "color": "#6bc8ea",
  "badges": [
    {
      "requiredStats": {
        "articlesEdited": 5
      }
    }, {
      "requiredStats": {
        "articlesEdited": 10
      }
    }, {
      "requiredStats": {
        "articlesEdited": 25
      }
    }, {
      "requiredStats": {
        "articlesEdited": 50
      }
    }, {
      "requiredStats": {
        "articlesEdited": 100
      }
    }
  ],
  "stats": {
    "articlesEdited": 0
  },
  "config": {
    "IncludeDeletedRevisions": false,
    "IncludeNamespaces": [],
    "IncludeNullRevisions": true,
    "IncludeRedirects": true
  },
  "Hooks": {
    "PageSaveComplete": "tryAchieve"
  },
  "MessagesDirs": [
    "i18n"
  ]
}

=== wikianesthesia/mediawiki-extensions-UserAchievements/achievements/TalkEdits/achievement.json
{
  "author": [
    "Chris Rishel"
  ],
  "version": "1.0",
  "priority": 90,
  "levels": 5,
  "color": "#f7e20a",
  "badges": [
    {
      "requiredStats": {
        "talkEdits": 1
      }
    }, {
      "requiredStats": {
        "talkEdits": 10
      }
    }, {
      "requiredStats": {
        "talkEdits": 100
      }
    }, {
      "requiredStats": {
        "talkEdits": 500
      }
    }, {
      "requiredStats": {
        "talkEdits": 1000
      }
    }
  ],
  "stats": {
    "talkEdits": 0
  },
  "config": {
    "IncludeDeletedRevisions": false,
    "IncludeNamespaces": [],
    "IncludeNullRevisions": true,
    "IncludeRedirects": true
  },
  "Hooks": {
    "PageSaveComplete": "tryAchieve"
  },
  "MessagesDirs": [
    "i18n"
  ]
}

=== wikianesthesia/mediawiki-extensions-UserAchievements/achievements/Edits/achievement.json
{
  "author": [
    "Chris Rishel"
  ],
  "version": "1.0",
  "priority": 200,
  "levels": 5,
  "color": "#f57921",
  "badges": [
    {
      "requiredStats": {
        "edits": 10
      }
    }, {
      "requiredStats": {
        "edits": 50
      }
    }, {
      "requiredStats": {
        "edits": 250
      }
    }, {
      "requiredStats": {
        "edits": 500
      }
    }, {
      "requiredStats": {
        "edits": 1000
      }
    }
  ],
  "stats": {
    "edits": 0
  },
  "config": {
    "IncludeDeletedRevisions": false,
    "IncludeNamespaces": [],
    "IncludeNullRevisions": true,
    "IncludeRedirects": true
  },
  "Hooks": {
    "PageSaveComplete": "tryAchieve"
  },
  "MessagesDirs": [
    "i18n"
  ]
}

=== wikianesthesia/mediawiki-extensions-UserAchievements/achievements/ArticlesCreated/achievement.json
{
  "class": "MediaWiki\\Extension\\UserAchievements\\Achievement\\ArticlesCreated",
  "version": "1.0",
  "author": [
    "Chris Rishel"
  ],
  "priority": 125,
  "levels": 5,
  "color": "#b6b2a9",
  "badges": [
    {
      "requiredStats": {
        "articlesCreated": 1
      }
    }, {
      "requiredStats": {
        "articlesCreated": 10
      }
    }, {
      "requiredStats": {
        "articlesCreated": 25
      }
    }, {
      "requiredStats": {
        "articlesCreated": 50
      }
    }, {
      "requiredStats": {
        "articlesCreated": 100
      }
    }
  ],
  "stats": {
    "articlesCreated": 0
  },
  "config": {
    "IncludeDeletedRevisions": false,
    "IncludeNamespaces": [],
    "IncludeNullRevisions": true,
    "IncludeRedirects": true
  },
  "Hooks": {
    "PageSaveComplete": "tryAchieve"
  },
  "MessagesDirs": [
    "i18n"
  ]
}

=== wikianesthesia/mediawiki-extensions-UserAchievements/achievements/PracticeGroupEdits/achievement.json
{
  "class": "MediaWiki\\Extension\\UserAchievements\\Achievement\\PracticeGroupEdits",
  "version": "1.0",
  "author": [
    "Chris Rishel"
  ],
  "priority": 75,
  "levels": 5,
  "color": "#f15563",
  "badges": [
    {
      "requiredStats": {
        "practiceGroupEdits": 10
      }
    }, {
      "requiredStats": {
        "practiceGroupEdits": 50
      }
    }, {
      "requiredStats": {
        "practiceGroupEdits": 250
      }
    }, {
      "requiredStats": {
        "practiceGroupEdits": 500
      }
    }, {
      "requiredStats": {
        "practiceGroupEdits": 1000
      }
    }
  ],
  "stats": {
    "practiceGroupEdits": 0
  },
  "config": {
    "IncludeDeletedRevisions": false,
    "IncludeNamespaces": [ 7740 ],
    "IncludeNullRevisions": true,
    "IncludeRedirects": true
  },
  "Hooks": {
    "PageSaveComplete": "tryAchieve"
  },
  "MessagesDirs": [
    "i18n"
  ]
}
